<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Admin Migration Tracker
    |--------------------------------------------------------------------------
    |
    | Inventory of legacy admin routes and migration status to Filament.
    | status: cutover_live | in_progress | planned | no_equivalent
    | priority: P1 (highest) ... P3 (lowest)
    |
    */
    'inventory' => [
        [
            'label' => 'Employees (Card/List)',
            'legacy_path' => 'all/employee/card',
            'filament_path' => '/admin/employees',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'People Ops',
        ],
        [
            'label' => 'Departments',
            'legacy_path' => 'form/departments/page',
            'filament_path' => '/admin/departments',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'People Ops',
        ],
        [
            'label' => 'Designations',
            'legacy_path' => 'form/designations/page',
            'filament_path' => '/admin/position-types',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'People Ops',
        ],
        [
            'label' => 'Holidays',
            'legacy_path' => 'form/holidays/new',
            'filament_path' => '/admin/holidays',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Time & Attendance',
        ],
        [
            'label' => 'Leave Requests',
            'legacy_path' => 'form/leaves/new',
            'filament_path' => '/admin/leaves-admins',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Time & Attendance',
        ],
        [
            'label' => 'Attendance',
            'legacy_path' => 'attendance/page',
            'filament_path' => '/admin/attendance-records',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Time & Attendance',
        ],
        [
            'label' => 'Leave Settings',
            'legacy_path' => 'form/leavesettings/page',
            'filament_path' => '/admin/leave-settings',
            'status' => 'cutover_live',
            'priority' => 'P2',
            'owner' => 'Time & Attendance',
        ],
        [
            'label' => 'Shift Scheduling',
            'legacy_path' => 'form/shiftscheduling/page',
            'filament_path' => '/admin/shift-scheduling',
            'status' => 'cutover_live',
            'priority' => 'P2',
            'owner' => 'Time & Attendance',
        ],
        [
            'label' => 'Shift List',
            'legacy_path' => 'form/shiftlist/page',
            'filament_path' => '/admin/shift-scheduling',
            'status' => 'cutover_live',
            'priority' => 'P2',
            'owner' => 'Time & Attendance',
        ],
        [
            'label' => 'Timesheets',
            'legacy_path' => 'form/timesheet/page',
            'filament_path' => '/admin/timesheet-entries',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Time & Attendance',
        ],
        [
            'label' => 'Overtime',
            'legacy_path' => 'form/overtime/page',
            'filament_path' => '/admin/overtime-entries',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Time & Attendance',
        ],
        [
            'label' => 'Payroll',
            'legacy_path' => 'form/salary/page',
            'filament_path' => '/admin/staff-salaries',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Payroll',
        ],
        [
            'label' => 'Payroll Items',
            'legacy_path' => 'form/payroll/items',
            'filament_path' => '/admin/payroll-policy-sets',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Payroll',
        ],
        [
            'label' => 'Reports Hub',
            'legacy_path' => 'form/employee/reports/page',
            'filament_path' => '/admin/reports-hub',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Reports',
        ],
        [
            'label' => 'Expense Reports',
            'legacy_path' => 'form/expense/reports/page',
            'filament_path' => '/admin/reports-hub',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Reports',
        ],
        [
            'label' => 'Invoice Reports',
            'legacy_path' => 'form/invoice/reports/page',
            'filament_path' => '/admin/reports-hub',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Reports',
        ],
        [
            'label' => 'Legacy Performance Form',
            'legacy_path' => 'form/performance/page',
            'filament_path' => '/admin/performance-hub',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Performance',
        ],
        [
            'label' => 'Legacy Performance Indicator',
            'legacy_path' => 'form/performance/indicator/page',
            'filament_path' => '/admin/performance-hub',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Performance',
        ],
        [
            'label' => 'Legacy Performance Appraisal',
            'legacy_path' => 'form/performance/appraisal/page',
            'filament_path' => '/admin/performance-hub',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Performance',
        ],
        [
            'label' => 'Performance Team Reviews',
            'legacy_path' => 'performance/team/reviews',
            'filament_path' => '/admin/performance-hub',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Performance',
        ],
        [
            'label' => 'Performance Team Annual',
            'legacy_path' => 'performance/team/annual-reviews',
            'filament_path' => '/admin/performance-hub',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Performance',
        ],
        [
            'label' => 'Performance Settings',
            'legacy_path' => 'performance/settings/page',
            'filament_path' => '/admin/performance-settings',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Performance',
        ],
        [
            'label' => 'Company Settings',
            'legacy_path' => 'company/settings/page',
            'filament_path' => '/admin/company-settings',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Settings',
        ],
        [
            'label' => 'Localization',
            'legacy_path' => 'localization/page',
            'filament_path' => '/admin/company-settings',
            'status' => 'cutover_live',
            'priority' => 'P2',
            'owner' => 'Settings',
        ],
        [
            'label' => 'Roles & Permissions',
            'legacy_path' => 'roles/permissions/page',
            'filament_path' => '/admin/roles-permissions',
            'status' => 'cutover_live',
            'priority' => 'P1',
            'owner' => 'Settings',
        ],
        [
            'label' => 'Salary Defaults',
            'legacy_path' => 'salary/settings/page',
            'filament_path' => '/admin/payroll-defaults',
            'status' => 'cutover_live',
            'priority' => 'P2',
            'owner' => 'Payroll',
        ],
        [
            'label' => 'Email Settings',
            'legacy_path' => 'email/settings/page',
            'filament_path' => '/admin/email-settings',
            'status' => 'cutover_live',
            'priority' => 'P2',
            'owner' => 'Settings',
        ],
        [
            'label' => 'Training Sessions',
            'legacy_path' => 'form/training/list/page',
            'filament_path' => '/admin/trainings',
            'status' => 'cutover_live',
            'priority' => 'P2',
            'owner' => 'People Ops',
        ],
        [
            'label' => 'Trainers',
            'legacy_path' => 'form/trainers/list/page',
            'filament_path' => '/admin/trainers',
            'status' => 'cutover_live',
            'priority' => 'P2',
            'owner' => 'People Ops',
        ],
        [
            'label' => 'Training Types',
            'legacy_path' => 'form/training/type/list/page',
            'filament_path' => '/admin/training-types',
            'status' => 'cutover_live',
            'priority' => 'P2',
            'owner' => 'People Ops',
        ],
    ],
];
